services:
  # Consul
  consul-server:
    image: hashicorp/consul:1.14.2
    container_name: consul-server
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
  consul-client:
    image: hashicorp/consul:1.14.2
    container_name: consul-client
    restart: always
    command: "agent -node=client-1 -join=consul-server"
