services:
  # Consul
  consul-server:
    image: hashicorp/consul:1.14.2
    container_name: consul-server
    restart: always
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
      - "53:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -recursor=8.8.8.8"

  consul-client:
    image: hashicorp/consul:1.14.2
    container_name: consul-client
    restart: always
    command: "agent -node=client-1 -join=consul-server"

  # Services
  # https://hub.docker.com/r/hashicorp/counting-service
  counting-service-green:
    image: hashicorp/counting-service:0.0.2
    container_name: counting-service-green
    ports:
      - "9001:9001"

  counting-service-blue:
    image: hashicorp/counting-service:0.0.2
    container_name: counting-service-blue
    environment:
      - PORT=9000
    ports:
      - "9000:9000"

  # https://hub.docker.com/r/hashicorp/dashboard-service
  dashboard-service:
    image: hashicorp/dashboard-service:0.0.4
    container_name: dashboard-service
    environment:
      - COUNTING_SERVICE_URL=http://counting-service-green:9001
    ports:
      - "9002:9002"
